coverage:
  status:
    project:
      is:
        flags: is
      visit:
        flags: visit
    patch:
      is:
        flags: is
      visit:
        flags: visit

flags:
  is:
    paths:
      - packages/parse5-is/**/*
  visit:
    paths:
      - packages/parse5-visit/**/*
